source("loadData.R")
data <- loadData()
png(filename='plot2.png', width=480, height=480, units='px')
plot(data$Global_active_power ~ data$dateTime, type="l", ylab="Global Active Power (kilowatts)", xlab="")
dev.off()